db:
  driver: sqlite3
  path: ./internal/db/sqlite3/are_you_free.db
  file: ./internal/db/sqlite3/are_you_free.sql

filepath:
  CSS: internal/web/static/css
  JS: internal/web/static/js
  image: internal/web/img
  icon: internal/web/icon

auth:
  session: someSessionName
  sessionKey: someSessionKey
  sessionPayh: /
  sessionExpirationSec: 86400
  sessionExpirationDay: 7
